# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'healthChecker' do
  pod 'Firebase/Core'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Pods for healthChecker


  target 'healthCheckerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'healthChecker-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for healthChecker-tvOS

  target 'healthChecker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
